{% set version = "4.3.2" %}

package:
  name: chaquopy-libzmq
  version: {{ version }}  # See buildutils/bundle.py in pyzmq

source:
  url: https://github.com/zeromq/libzmq/releases/download/v{{ version }}/zeromq-{{ version }}.tar.gz
