{% set version = "0.16.0" %}

package:
  name: rawpy
  version: {{ version }}

source:
  git_url: https://github.com/letmaik/rawpy
  git_rev: v{{ version }}

requirements:
  host:
    - python
    - numpy 1.17.4
    - chaquopy-libraw 0.20.2
