{% set version = "0.9.1" %}

package:
  name: torchvision
  version: {{ version }}

build:
  number: 1

source:
  git_url: https://github.com/pytorch/vision.git
  git_rev: v{{ version }}

requirements:
  host:
    - python
    - torch 1.8.1  # https://github.com/pytorch/vision/blob/master/README.rst
