{% set version = "0.23.90" %}

package:
  name: chaquopy-zbar
  version: {{ version }}

source:
  url: https://linuxtv.org/downloads/zbar/zbar-{{ version }}.tar.gz

requirements:
  host:
    - chaquopy-libiconv 1.16
