package:
  name: python_example
  version: 0.0.1

source:
  git_url: https://github.com/pybind/python_example.git
  git_rev: 08a2f37d8a58fb01612c901592db80713b300c53

requirements:
  build:
    # setup.py has pybind11 in setup_requires, but this doesn't work because the headers aren't
    # unpacked correctly (https://github.com/pybind/python_example/issues/16).
    - pybind11 2.3.0
  host:
    - python
